Fix CI

diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -32,6 +32,24 @@ jobs:
         path: |
           /home/runner/work/eqr/eqr/target/x86_64-unknown-linux-musl/release/qr
           /home/runner/work/eqr/eqr/target/x86_64-unknown-linux-musl/release/promptpay
+  style:
+    name: Check Style
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      - name: Install Rust
+        uses: dtolnay/rust-toolchain@stable
+        with:
+          components: rustfmt
+
+      - name: cargo fmt --check
+        run: |
+          if ! rustfmt --check --edition 2021 $(git ls-files '*.rs'); then
+            printf "Please run \`rustfmt --edition 2021 \$(git ls-files '*.rs')\` to fix rustfmt errors.\nSee docs/CODE_STYLE.md for more details.\n" >&2
+            exit 1
+          fi
   minimal-versions:
     runs-on: ubuntu-latest
     needs: [style]
